title: "Lukas Hajdu"
baseurl: "https://lukashajdu.com/"
publishDir: web
paginate: 20
disqusShortname: "lukashajdu-com"
googleAnalytics: "G-P3FBCQN2TP"

params:
  sitename: "blog@lukash:/en"
  author: "Lukas Hajdu"
  dateform: "Monday, Jan 2, 2006"
  schemaDate: "2006-01-02"

theme: "hugo-black-and-light-theme"
PygmentsUseClasses: false
PygmentsCodeFences: true
PygmentsStyle: "friendly"

languageCode: "en"
language: "en"

taxonomies:
  tag: "tags"
  category: "categories"

menu:
  main:
    - name: "About"
      url: "https://www.linkedin.com/in/lhajdu/"
